export const SERVICE_OPTIONS = [
  'Car lockout',
  'Car key replacement',
  'Lost all keys',
  'Key fob programming',
  'Transponder key programming',
  'Ignition repair / replacement',
  'Broken key extraction',
  'Trunk lockout',
  'Remote battery / remote issue',
  'Other automotive locksmith service',
]

export const VEHICLE_MODELS: Record<string, string[]> = {
  Acura: ['ILX', 'Integra', 'TLX', 'RDX', 'MDX', 'Other Acura'],
  Audi: ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron', 'Other Audi'],
  BMW: ['2 Series', '3 Series', '4 Series', '5 Series', '7 Series', 'X1', 'X3', 'X5', 'X7', 'i4', 'iX', 'Other BMW'],
  Buick: ['Encore', 'Encore GX', 'Envision', 'Enclave', 'Other Buick'],
  Cadillac: ['CT4', 'CT5', 'CT6', 'XT4', 'XT5', 'XT6', 'Escalade', 'Other Cadillac'],
  Chevrolet: ['Cruze', 'Malibu', 'Impala', 'Camaro', 'Corvette', 'Trax', 'Trailblazer', 'Equinox', 'Blazer', 'Traverse', 'Tahoe', 'Suburban', 'Colorado', 'Silverado 1500', 'Silverado HD', 'Bolt EV', 'Other Chevrolet'],
  Chrysler: ['200', '300', 'Pacifica', 'Town & Country', 'Voyager', 'Other Chrysler'],
  Dodge: ['Charger', 'Challenger', 'Durango', 'Journey', 'Grand Caravan', 'Hornet', 'Other Dodge'],
  Ford: ['Fiesta', 'Focus', 'Fusion', 'Taurus', 'Mustang', 'EcoSport', 'Escape', 'Edge', 'Explorer', 'Expedition', 'Bronco', 'Bronco Sport', 'Maverick', 'Ranger', 'F-150', 'F-250', 'F-350', 'Transit', 'Other Ford'],
  Genesis: ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80', 'Other Genesis'],
  GMC: ['Terrain', 'Acadia', 'Yukon', 'Canyon', 'Sierra 1500', 'Sierra HD', 'Savana', 'Other GMC'],
  Honda: ['Fit', 'Civic', 'Accord', 'HR-V', 'CR-V', 'Passport', 'Pilot', 'Odyssey', 'Ridgeline', 'Other Honda'],
  Hyundai: ['Accent', 'Elantra', 'Sonata', 'Veloster', 'Venue', 'Kona', 'Tucson', 'Santa Fe', 'Palisade', 'Ioniq', 'Ioniq 5', 'Ioniq 6', 'Santa Cruz', 'Other Hyundai'],
  Infiniti: ['Q50', 'Q60', 'QX30', 'QX50', 'QX55', 'QX60', 'QX80', 'Other Infiniti'],
  Jaguar: ['XE', 'XF', 'XJ', 'F-Type', 'E-Pace', 'F-Pace', 'I-Pace', 'Other Jaguar'],
  Jeep: ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Gladiator', 'Wagoneer', 'Grand Wagoneer', 'Other Jeep'],
  Kia: ['Rio', 'Forte', 'K5', 'Optima', 'Stinger', 'Soul', 'Seltos', 'Sportage', 'Sorento', 'Telluride', 'Carnival', 'Niro', 'EV6', 'Other Kia'],
  LandRover: ['Discovery Sport', 'Discovery', 'Range Rover Evoque', 'Range Rover Velar', 'Range Rover Sport', 'Range Rover', 'Defender', 'Other Land Rover'],
  Lexus: ['IS', 'ES', 'GS', 'LS', 'UX', 'NX', 'RX', 'GX', 'LX', 'RC', 'LC', 'Other Lexus'],
  Lincoln: ['MKZ', 'Continental', 'Corsair', 'Nautilus', 'Aviator', 'Navigator', 'Other Lincoln'],
  Mazda: ['Mazda3', 'Mazda6', 'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-9', 'CX-90', 'MX-5 Miata', 'Other Mazda'],
  MercedesBenz: ['A-Class', 'C-Class', 'E-Class', 'S-Class', 'CLA', 'CLS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'G-Class', 'Sprinter', 'Metris', 'Other Mercedes-Benz'],
  Mini: ['Cooper', 'Cooper S', 'Clubman', 'Countryman', 'Other MINI'],
  Mitsubishi: ['Mirage', 'Lancer', 'Outlander Sport', 'Outlander', 'Eclipse Cross', 'Other Mitsubishi'],
  Nissan: ['Versa', 'Sentra', 'Altima', 'Maxima', 'Leaf', 'Kicks', 'Rogue Sport', 'Rogue', 'Murano', 'Pathfinder', 'Armada', 'Frontier', 'Titan', 'Z', 'Other Nissan'],
  Porsche: ['718', '911', 'Panamera', 'Macan', 'Cayenne', 'Taycan', 'Other Porsche'],
  Ram: ['1500', '2500', '3500', 'ProMaster', 'ProMaster City', 'Other Ram'],
  Subaru: ['Impreza', 'Legacy', 'WRX', 'BRZ', 'Crosstrek', 'Forester', 'Outback', 'Ascent', 'Other Subaru'],
  Tesla: ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck', 'Other Tesla'],
  Toyota: ['Yaris', 'Corolla', 'Camry', 'Avalon', 'Prius', 'C-HR', 'Corolla Cross', 'RAV4', 'Venza', 'Highlander', '4Runner', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'GR86', 'Supra', 'Other Toyota'],
  Volkswagen: ['Golf', 'GTI', 'Jetta', 'Passat', 'Arteon', 'Beetle', 'Taos', 'Tiguan', 'Atlas', 'ID.4', 'Other Volkswagen'],
  Volvo: ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'C40', 'Other Volvo'],
  Other: ['Other / Not listed'],
}

export const MAKE_LABELS: Record<string, string> = {
  LandRover: 'Land Rover',
  MercedesBenz: 'Mercedes-Benz',
}
