insert into public.site_content_blocks
(locale, page_key, slot, eyebrow, title, body, items, cta_label, cta_href, sort_order, is_published)
values
-- EN / HOME
('en', 'home', 'service-depth', 'Locksmith service coverage', 'Complete mobile locksmith service', 'Full-service locksmith help includes emergency lockouts, car keys, rekeys, residential locks, commercial locks, safe opening, access control, and urgent service calls.', '["Emergency, automotive, residential, and commercial service", "Smart locks, safe opening, and access control", "Clear descriptions for customers"]'::jsonb, 'View services', '/en/services', 10, true),
('en', 'home', 'customer-info', 'Before service', 'Information customers should prepare', 'Send the service type, location, urgency, authorization details, contact phone number, and vehicle information when relevant.', '["Service type and exact location", "Authorization or access details", "Vehicle make, model, and year when relevant", "Phone number for confirmation"]'::jsonb, 'Request service', '/en/contact#request-service', 20, true),
('en', 'home', 'area-section', 'Local coverage', 'Mobile service areas', 'Mobile locksmith service is available across Philadelphia and nearby coverage areas for automotive, residential, commercial, and emergency needs.', '["Coverage depends on technician availability", "Response time depends on location and urgency", "Local pages explain common services"]'::jsonb, 'View areas', '/en/areas', 30, true),

-- EN / SERVICE DETAIL
('en', 'service-detail', 'hero', 'Locksmith service', '', 'Service details explain what customers can request, what information is helpful, and what factors may affect availability, pricing, and timing.', '[]'::jsonb, 'Call now', 'tel:+12676122555', 10, true),
('en', 'service-detail', 'overview', 'Service overview', 'What this service includes', 'Service details, preparation steps, and timing factors are confirmed before work begins.', '[]'::jsonb, null, null, 20, true),
('en', 'service-detail', 'readiness', null, 'Information customers should prepare', 'Service type, exact location, phone number, urgency, authorization details, and vehicle information when relevant help make the request actionable.', '["Service type and access details", "Exact location", "Current key, lock, door, safe, mailbox, or vehicle situation", "Phone number for confirmation"]'::jsonb, null, null, 30, true),
('en', 'service-detail', 'pricing', null, 'What affects price and timing', 'Final price and service time may depend on service type, lock or key system, parts availability, programming requirements, distance, time of day, authorization, and job complexity.', '["Lock or key system", "Parts availability", "Programming requirements", "Distance and timing", "Authorization and job complexity"]'::jsonb, null, null, 40, true),
('en', 'service-detail', 'authorization', null, 'Authorization and safety', 'Customers may need to confirm authorization to access or service a vehicle, property, door, lock, safe, mailbox, or access-control system before work begins.', '["Proof of ownership or authorization may be requested", "Details are confirmed before service", "Safety and fraud prevention matter"]'::jsonb, null, null, 50, true),
('en', 'service-detail', 'process', 'How service works', 'Service request process', 'This section explains the customer journey from request to confirmation.', '["Submit service details and location", "Confirm urgency, authorization, and phone number", "Review availability, tools, parts, and compatibility", "Confirm next step before service begins"]'::jsonb, null, null, 60, true),

-- EN / AREA DETAIL
('en', 'area-detail', 'hero', 'Local locksmith coverage', '', 'This area page explains mobile locksmith availability, common services, and customer preparation for this service area.', '[]'::jsonb, 'Call now', 'tel:+12676122555', 10, true),
('en', 'area-detail', 'overview', 'Area overview', 'Mobile coverage information', 'Local service details, common locksmith needs, and preparation notes are listed for this coverage area.', '[]'::jsonb, null, null, 20, true),
('en', 'area-detail', 'prep', null, 'What to prepare before service', 'Customers should prepare service details and location information before requesting mobile service.', '["Service needed and exact location", "Lock, door, safe, mailbox, or access-control details", "Vehicle make, model, and year when relevant", "Whether keys are lost, broken, locked in, or not programming", "Phone number for fast confirmation"]'::jsonb, null, null, 30, true),
('en', 'area-detail', 'supported-services', null, 'Services commonly requested here', 'This section explains common locksmith services requested in local coverage pages.', '["Emergency locksmith 24/7", "Car lockout help", "Rekey service", "Commercial locksmith", "Residential locksmith"]'::jsonb, null, null, 40, true),
('en', 'area-detail', 'local-info', null, 'Local service information', 'Local availability depends on technician schedule, location, service type, parts, traffic, weather, and urgency.', '["Mobile service depends on technician availability and location", "Response times may vary by traffic, distance, weather, and urgency", "Final price depends on service details, parts, authorization, and job complexity"]'::jsonb, null, null, 50, true),
('en', 'area-detail', 'coverage-notes', null, 'Coverage notes', 'Service-area details are confirmed before work begins.', '["Coverage can vary by time and technician availability", "Some services require specific parts or programming tools", "Service details are confirmed before work begins"]'::jsonb, null, null, 60, true),

-- ES / HOME
('es', 'home', 'service-depth', 'Cobertura de cerrajería', 'Servicio móvil completo de cerrajería', 'Ayuda completa para emergencias, llaves de auto, rekeys, cerraduras residenciales, cerraduras comerciales, cajas fuertes, access control y llamadas urgentes.', '["Servicio de emergencia, auto, residencial y comercial", "Smart locks, cajas fuertes y access control", "Descripciones claras para clientes"]'::jsonb, 'Ver servicios', '/es/services', 10, true),
('es', 'home', 'customer-info', 'Antes del servicio', 'Información que el cliente debe preparar', 'Envíe tipo de servicio, ubicación, urgencia, autorización, teléfono y datos del vehículo cuando aplique.', '["Tipo de servicio y ubicación exacta", "Autorización o detalles de acceso", "Marca, modelo y año cuando aplique", "Teléfono para confirmación"]'::jsonb, 'Solicitar servicio', '/es/contact#request-service', 20, true),
('es', 'home', 'area-section', 'Cobertura local', 'Áreas de servicio móvil', 'Servicio móvil de cerrajería en Philadelphia y áreas cercanas para necesidades de auto, hogar, negocio y emergencia.', '["La cobertura depende de disponibilidad", "El tiempo depende de ubicación y urgencia", "Las páginas locales explican servicios comunes"]'::jsonb, 'Ver áreas', '/es/areas', 30, true),

-- ES / SERVICE DETAIL
('es', 'service-detail', 'hero', 'Servicio de cerrajería', '', 'Esta página explica qué puede solicitar el cliente, qué datos ayudan y qué puede afectar disponibilidad, precio y tiempo.', '[]'::jsonb, 'Llamar ahora', 'tel:+12676122555', 10, true),
('es', 'service-detail', 'overview', 'Resumen del servicio', 'Qué incluye este servicio', 'Detalles del servicio, preparación y tiempos se confirman antes de comenzar.', '[]'::jsonb, null, null, 20, true),
('es', 'service-detail', 'readiness', null, 'Información que el cliente debe preparar', 'Tipo de servicio, ubicación exacta, teléfono, urgencia, autorización y datos del vehículo cuando aplique hacen la solicitud más clara.', '["Tipo de servicio y acceso", "Ubicación exacta", "Situación de llave, cerradura, puerta, caja fuerte, buzón o vehículo", "Teléfono para confirmación"]'::jsonb, null, null, 30, true),
('es', 'service-detail', 'pricing', null, 'Qué afecta precio y tiempo', 'El precio y tiempo final pueden depender del tipo de servicio, sistema de cerradura o llave, piezas, programación, distancia, horario, autorización y complejidad.', '["Sistema de cerradura o llave", "Disponibilidad de piezas", "Programación requerida", "Distancia y horario", "Autorización y complejidad"]'::jsonb, null, null, 40, true),
('es', 'service-detail', 'authorization', null, 'Autorización y seguridad', 'El cliente puede necesitar confirmar autorización para acceder o trabajar en vehículo, propiedad, puerta, cerradura, caja fuerte, buzón o access-control antes del servicio.', '["Puede requerirse prueba de autorización", "Los detalles se confirman antes", "La seguridad y prevención de fraude importan"]'::jsonb, null, null, 50, true),
('es', 'service-detail', 'process', 'Cómo funciona el servicio', 'Proceso de solicitud', 'Esta sección explica el camino del cliente desde la solicitud hasta la confirmación.', '["Enviar detalles y ubicación", "Confirmar urgencia, autorización y teléfono", "Revisar disponibilidad, herramientas, piezas y compatibilidad", "Confirmar siguiente paso antes del servicio"]'::jsonb, null, null, 60, true),

-- ES / AREA DETAIL
('es', 'area-detail', 'hero', 'Cobertura local de cerrajería', '', 'Esta página explica disponibilidad móvil, servicios comunes y preparación del cliente en esta área.', '[]'::jsonb, 'Llamar ahora', 'tel:+12676122555', 10, true),
('es', 'area-detail', 'overview', 'Resumen del área', 'Información de cobertura móvil', 'Detalles locales, necesidades comunes y preparación se listan para esta área de cobertura.', '[]'::jsonb, null, null, 20, true),
('es', 'area-detail', 'prep', null, 'Qué preparar antes del servicio', 'El cliente debe preparar detalles del servicio y ubicación antes de solicitar servicio móvil.', '["Servicio requerido y ubicación exacta", "Detalles de cerradura, puerta, caja fuerte, buzón o access-control", "Marca, modelo y año cuando aplique", "Si las llaves están perdidas, rotas, encerradas o no programan", "Teléfono para confirmación"]'::jsonb, null, null, 30, true),
('es', 'area-detail', 'supported-services', null, 'Servicios comunes aquí', 'Esta sección explica servicios comunes en páginas locales.', '["Cerrajero de emergencia 24/7", "Bloqueo de automóvil", "Rekey", "Cerrajero comercial", "Cerrajero residencial"]'::jsonb, null, null, 40, true),
('es', 'area-detail', 'local-info', null, 'Información local', 'La disponibilidad local depende de agenda, ubicación, tipo de servicio, piezas, tráfico, clima y urgencia.', '["Servicio móvil depende de disponibilidad y ubicación", "El tiempo varía por tráfico, distancia, clima y urgencia", "El precio depende de servicio, piezas, autorización y complejidad"]'::jsonb, null, null, 50, true),
('es', 'area-detail', 'coverage-notes', null, 'Notas de cobertura', 'Aclare límites de cobertura y expectativas del cliente.', '["La cobertura puede variar por horario y disponibilidad", "Algunos vehículos requieren piezas o herramientas específicas", "Los detalles se confirman antes del servicio"]'::jsonb, null, null, 60, true),

-- RU / HOME
('ru', 'home', 'service-depth', 'Locksmith-сервис', 'Полный мобильный locksmith-сервис', 'Полный сервис включает emergency lockouts, автомобильные ключи, rekeys, residential locks, commercial locks, safe opening, access control и срочные вызовы.', '["Emergency, automotive, residential и commercial service", "Smart locks, safe opening и access control", "Понятные описания для клиентов"]'::jsonb, 'Смотреть услуги', '/ru/services', 10, true),
('ru', 'home', 'customer-info', 'Перед сервисом', 'Что клиенту подготовить', 'Отправьте тип услуги, локацию, срочность, право доступа, телефон и данные автомобиля, когда это применимо.', '["Тип услуги и точная локация", "Авторизация или детали доступа", "Марка, модель и год когда применимо", "Телефон для подтверждения"]'::jsonb, 'Оставить заявку', '/ru/contact#request-service', 20, true),
('ru', 'home', 'area-section', 'Локальное покрытие', 'Районы мобильного сервиса', 'Мобильный locksmith-сервис доступен в Philadelphia и ближайших районах для авто, дома, бизнеса и срочных ситуаций.', '["Покрытие зависит от доступности", "Время зависит от локации и срочности", "Локальные страницы объясняют частые услуги"]'::jsonb, 'Смотреть районы', '/ru/areas', 30, true),

-- RU / SERVICE DETAIL
('ru', 'service-detail', 'hero', 'Locksmith-услуга', '', 'Эта страница объясняет, что клиент может запросить, какие данные помогают и что влияет на доступность, цену и сроки.', '[]'::jsonb, 'Позвонить', 'tel:+12676122555', 10, true),
('ru', 'service-detail', 'overview', 'Описание услуги', 'Что включает услуга', 'Детали услуги, подготовка и сроки подтверждаются до начала работы.', '[]'::jsonb, null, null, 20, true),
('ru', 'service-detail', 'readiness', null, 'Что клиенту подготовить', 'Тип услуги, точная локация, телефон, срочность, право доступа и данные автомобиля когда применимо помогают быстрее подготовить сервис.', '["Тип услуги и детали доступа", "Точная локация", "Ситуация с ключом, замком, дверью, сейфом, mailbox или авто", "Телефон для подтверждения"]'::jsonb, null, null, 30, true),
('ru', 'service-detail', 'pricing', null, 'Что влияет на цену и сроки', 'Финальная цена и время могут зависеть от типа услуги, системы замка или ключа, наличия деталей, программирования, расстояния, времени, авторизации и сложности.', '["Система замка или ключа", "Наличие деталей", "Необходимость программирования", "Расстояние и время", "Авторизация и сложность"]'::jsonb, null, null, 40, true),
('ru', 'service-detail', 'authorization', null, 'Авторизация и безопасность', 'Клиенту может потребоваться подтвердить право доступа к автомобилю, property, двери, замку, сейфу, mailbox или access-control system до начала работы.', '["Может потребоваться подтверждение права", "Детали подтверждаются до начала", "Безопасность и защита от мошенничества важны"]'::jsonb, null, null, 50, true),
('ru', 'service-detail', 'process', 'Как проходит сервис', 'Процесс заявки', 'Этот блок объясняет путь клиента от заявки до подтверждения.', '["Отправить детали услуги и локацию", "Подтвердить срочность, авторизацию и телефон", "Проверить доступность, инструменты, детали и совместимость", "Подтвердить следующий шаг до начала услуги"]'::jsonb, null, null, 60, true),

-- RU / AREA DETAIL
('ru', 'area-detail', 'hero', 'Локальное locksmith-покрытие', '', 'Эта страница объясняет мобильную доступность, частые услуги и подготовку клиента в этом районе.', '[]'::jsonb, 'Позвонить', 'tel:+12676122555', 10, true),
('ru', 'area-detail', 'overview', 'Описание района', 'Информация о мобильном покрытии', 'Локальные детали сервиса, частые locksmith-задачи и подготовка указаны для этого района.', '[]'::jsonb, null, null, 20, true),
('ru', 'area-detail', 'prep', null, 'Что подготовить перед услугой', 'Клиент должен подготовить детали услуги и локацию перед запросом мобильного сервиса.', '["Нужная услуга и точная локация", "Детали замка, двери, сейфа, mailbox или access-control", "Марка, модель и год когда применимо", "Потеряны, сломаны, закрыты внутри или не программируются ли ключи", "Телефон для быстрого подтверждения"]'::jsonb, null, null, 30, true),
('ru', 'area-detail', 'supported-services', null, 'Частые услуги здесь', 'Этот блок объясняет частые locksmith-услуги на локальных страницах.', '["Emergency locksmith 24/7", "Car lockout help", "Rekey service", "Commercial locksmith", "Residential locksmith"]'::jsonb, null, null, 40, true),
('ru', 'area-detail', 'local-info', null, 'Локальная информация', 'Локальная доступность зависит от графика, локации, типа услуги, деталей, трафика, погоды и срочности.', '["Мобильный сервис зависит от доступности и локации", "Сроки зависят от трафика, расстояния, погоды и срочности", "Цена зависит от услуги, деталей, авторизации и сложности"]'::jsonb, null, null, 50, true),
('ru', 'area-detail', 'coverage-notes', null, 'Заметки по покрытию', 'Уточните ограничения покрытия и ожидания клиента.', '["Покрытие может меняться по времени и доступности", "Некоторые авто требуют специальные детали или инструменты", "Детали подтверждаются до начала услуги"]'::jsonb, null, null, 60, true)
on conflict do nothing;
