insert into public.site_content_blocks
(locale, page_key, slot, eyebrow, title, body, items, cta_label, cta_href, sort_order, is_published)
values
-- EN / HOME
('en', 'home', 'service-depth', 'Automotive locksmith coverage', 'Complete mobile automotive locksmith support', 'Use this section to explain the main service categories customers can request, including lockouts, replacement keys, key fobs, transponder programming, broken key extraction, and ignition-related help.', '["Service details are managed from Services admin", "Use published services to control the cards", "Keep descriptions clear for Google Ads and customer trust"]'::jsonb, 'View services', '/en/services', 10, true),
('en', 'home', 'customer-info', 'Before requesting service', 'Information customers should prepare', 'Use this section to explain what customers should send before service: vehicle make, model, year, location, urgency, key situation, and contact phone number.', '["Vehicle make, model, and year", "Exact location or nearby landmark", "Whether all keys are lost", "Phone number for confirmation"]'::jsonb, 'Request service', '/en/contact#request-service', 20, true),
('en', 'home', 'area-section', 'Local coverage', 'Mobile service areas', 'Use this section to explain your coverage area and how mobile automotive locksmith requests are handled across Philadelphia and nearby locations.', '["Coverage depends on technician availability", "Response time depends on location and urgency", "Use area pages for local SEO and customer clarity"]'::jsonb, 'View areas', '/en/areas', 30, true),

-- EN / SERVICE DETAIL
('en', 'service-detail', 'hero', 'Automotive locksmith service', '', 'This service page explains what the customer can request, what details are needed, and what factors may affect availability, pricing, and timing.', '[]'::jsonb, 'Call now', 'tel:+12155550100', 10, true),
('en', 'service-detail', 'overview', 'Service overview', 'What this service includes', 'Use this block for general service-page explanation. The specific service title, intro, excerpt, and SEO fields still come from Services admin.', '[]'::jsonb, null, null, 20, true),
('en', 'service-detail', 'readiness', null, 'Information customers should prepare', 'Ask customers to provide vehicle make, model, year, current location, phone number, urgency, and whether all keys are lost.', '["Vehicle make, model, and year", "Exact location", "Current key situation", "Phone number for confirmation"]'::jsonb, null, null, 30, true),
('en', 'service-detail', 'pricing', null, 'What affects price and timing', 'Final price and service time may depend on vehicle security system, key type, parts availability, programming requirements, distance, time of day, and job complexity.', '["Vehicle security system", "Key or fob type", "Parts availability", "Programming requirements", "Distance and timing"]'::jsonb, null, null, 40, true),
('en', 'service-detail', 'authorization', null, 'Authorization and safety', 'Customers may need to confirm authorization to access or service the vehicle before work begins.', '["Proof of ownership or authorization may be requested", "Details are confirmed before service", "Safety and fraud prevention matter"]'::jsonb, null, null, 50, true),
('en', 'service-detail', 'process', 'How the request works', 'Service request process', 'Use this block to explain the customer journey from request to confirmation.', '["Submit service and vehicle details", "Confirm location, urgency, and phone number", "Review availability, parts, and programming needs", "Confirm next step before service begins"]'::jsonb, null, null, 60, true),

-- EN / AREA DETAIL
('en', 'area-detail', 'hero', 'Local automotive locksmith coverage', '', 'This area page explains mobile automotive locksmith availability, common requests, and customer preparation for this service area.', '[]'::jsonb, 'Call now', 'tel:+12155550100', 10, true),
('en', 'area-detail', 'overview', 'Area overview', 'Mobile coverage information', 'Use this block for general area-page explanation. The specific city, title, intro, supported services, and SEO fields still come from Areas admin.', '[]'::jsonb, null, null, 20, true),
('en', 'area-detail', 'prep', null, 'What to prepare before service', 'Customers should prepare vehicle details and location information before requesting mobile service.', '["Vehicle make, model, and year", "Exact address or landmark", "Whether all keys are lost", "Whether the vehicle is locked, running, or in a garage", "Phone number for fast confirmation"]'::jsonb, null, null, 30, true),
('en', 'area-detail', 'supported-services', null, 'Services commonly requested here', 'Use this block to explain the common automotive locksmith services requested in local coverage pages.', '["Car lockout help", "Replacement car keys", "Key fob and transponder programming", "Broken key extraction", "Ignition-related support"]'::jsonb, null, null, 40, true),
('en', 'area-detail', 'local-info', null, 'Local service information', 'Use this block to explain how service availability works locally.', '["Mobile service depends on technician availability and location", "Response times may vary by traffic, distance, weather, and urgency", "Final price depends on vehicle details, parts, and job complexity"]'::jsonb, null, null, 50, true),
('en', 'area-detail', 'coverage-notes', null, 'Coverage notes', 'Use this block to clarify service-area limitations and customer expectations.', '["Coverage can vary by time and technician availability", "Some vehicles require specific parts or programming tools", "Service details are confirmed before work begins"]'::jsonb, null, null, 60, true),

-- ES / HOME
('es', 'home', 'service-depth', 'Cobertura automotriz', 'Soporte móvil completo de cerrajería automotriz', 'Use esta sección para explicar las categorías principales: autos cerrados, reemplazo de llaves, controles, transponder, extracción de llave rota e ignición.', '["Los detalles se administran desde Services admin", "Las tarjetas usan servicios publicados", "Mantenga textos claros para Google Ads y confianza"]'::jsonb, 'Ver servicios', '/es/services', 10, true),
('es', 'home', 'customer-info', 'Antes de solicitar servicio', 'Información que el cliente debe preparar', 'Explique qué debe enviar el cliente: marca, modelo, año, ubicación, urgencia, situación de la llave y teléfono.', '["Marca, modelo y año", "Ubicación exacta o referencia", "Si perdió todas las llaves", "Teléfono para confirmación"]'::jsonb, 'Solicitar servicio', '/es/contact#request-service', 20, true),
('es', 'home', 'area-section', 'Cobertura local', 'Áreas de servicio móvil', 'Explique la cobertura y cómo se manejan las solicitudes móviles en Philadelphia y ubicaciones cercanas.', '["La cobertura depende de disponibilidad", "El tiempo depende de ubicación y urgencia", "Use páginas de áreas para SEO local"]'::jsonb, 'Ver áreas', '/es/areas', 30, true),

-- ES / SERVICE DETAIL
('es', 'service-detail', 'hero', 'Servicio automotriz', '', 'Esta página explica qué puede solicitar el cliente, qué datos se necesitan y qué puede afectar disponibilidad, precio y tiempo.', '[]'::jsonb, 'Llamar ahora', 'tel:+12155550100', 10, true),
('es', 'service-detail', 'overview', 'Resumen del servicio', 'Qué incluye este servicio', 'Use este bloque para la explicación general. El título, intro, extracto y SEO específicos vienen desde Services admin.', '[]'::jsonb, null, null, 20, true),
('es', 'service-detail', 'readiness', null, 'Información que el cliente debe preparar', 'Pida marca, modelo, año, ubicación actual, teléfono, urgencia y si perdió todas las llaves.', '["Marca, modelo y año", "Ubicación exacta", "Situación de la llave", "Teléfono para confirmación"]'::jsonb, null, null, 30, true),
('es', 'service-detail', 'pricing', null, 'Qué afecta precio y tiempo', 'El precio y tiempo final pueden depender del sistema de seguridad, tipo de llave, piezas, programación, distancia, horario y complejidad.', '["Sistema de seguridad", "Tipo de llave o control", "Disponibilidad de piezas", "Programación requerida", "Distancia y horario"]'::jsonb, null, null, 40, true),
('es', 'service-detail', 'authorization', null, 'Autorización y seguridad', 'El cliente puede necesitar confirmar autorización para acceder o trabajar en el vehículo antes del servicio.', '["Puede requerirse prueba de autorización", "Los detalles se confirman antes", "La seguridad y prevención de fraude importan"]'::jsonb, null, null, 50, true),
('es', 'service-detail', 'process', 'Cómo funciona la solicitud', 'Proceso de solicitud', 'Explique el camino del cliente desde la solicitud hasta la confirmación.', '["Enviar servicio y datos del vehículo", "Confirmar ubicación, urgencia y teléfono", "Revisar disponibilidad, piezas y programación", "Confirmar siguiente paso antes del servicio"]'::jsonb, null, null, 60, true),

-- ES / AREA DETAIL
('es', 'area-detail', 'hero', 'Cobertura local automotriz', '', 'Esta página explica disponibilidad móvil, solicitudes comunes y preparación del cliente en esta área.', '[]'::jsonb, 'Llamar ahora', 'tel:+12155550100', 10, true),
('es', 'area-detail', 'overview', 'Resumen del área', 'Información de cobertura móvil', 'Use este bloque para explicación general. La ciudad, título, intro, servicios y SEO vienen desde Areas admin.', '[]'::jsonb, null, null, 20, true),
('es', 'area-detail', 'prep', null, 'Qué preparar antes del servicio', 'El cliente debe preparar datos del vehículo y ubicación antes de solicitar servicio móvil.', '["Marca, modelo y año", "Dirección exacta o referencia", "Si perdió todas las llaves", "Si el auto está cerrado, encendido o en garaje", "Teléfono para confirmación"]'::jsonb, null, null, 30, true),
('es', 'area-detail', 'supported-services', null, 'Servicios comunes aquí', 'Explique servicios comunes solicitados en páginas locales.', '["Auto cerrado", "Reemplazo de llaves", "Programación de control y transponder", "Extracción de llave rota", "Soporte de ignición"]'::jsonb, null, null, 40, true),
('es', 'area-detail', 'local-info', null, 'Información local', 'Explique cómo funciona la disponibilidad local.', '["Servicio móvil depende de disponibilidad y ubicación", "El tiempo varía por tráfico, distancia, clima y urgencia", "El precio depende del vehículo, piezas y complejidad"]'::jsonb, null, null, 50, true),
('es', 'area-detail', 'coverage-notes', null, 'Notas de cobertura', 'Aclare límites de cobertura y expectativas del cliente.', '["La cobertura puede variar por horario y disponibilidad", "Algunos vehículos requieren piezas o herramientas específicas", "Los detalles se confirman antes del servicio"]'::jsonb, null, null, 60, true),

-- RU / HOME
('ru', 'home', 'service-depth', 'Автомобильный locksmith-сервис', 'Полная мобильная поддержка по автомобильным ключам', 'Используйте этот блок, чтобы объяснить основные категории услуг: открытие авто, замена ключей, брелки, transponder, извлечение сломанного ключа и помощь с зажиганием.', '["Детали услуг управляются в Services admin", "Карточки строятся из опубликованных услуг", "Тексты должны быть понятными для Google Ads и клиента"]'::jsonb, 'Смотреть услуги', '/ru/services', 10, true),
('ru', 'home', 'customer-info', 'Перед заявкой', 'Что клиенту подготовить', 'Объясните, что клиент должен отправить: марка, модель, год, локация, срочность, ситуация с ключом и номер телефона.', '["Марка, модель и год", "Точный адрес или ориентир", "Потеряны ли все ключи", "Телефон для подтверждения"]'::jsonb, 'Оставить заявку', '/ru/contact#request-service', 20, true),
('ru', 'home', 'area-section', 'Локальное покрытие', 'Районы мобильного сервиса', 'Объясните покрытие и как обрабатываются мобильные заявки в Philadelphia и ближайших районах.', '["Покрытие зависит от доступности", "Время зависит от локации и срочности", "Страницы районов помогают local SEO"]'::jsonb, 'Смотреть районы', '/ru/areas', 30, true),

-- RU / SERVICE DETAIL
('ru', 'service-detail', 'hero', 'Автомобильная услуга', '', 'Эта страница объясняет, что клиент может запросить, какие данные нужны и что влияет на доступность, цену и сроки.', '[]'::jsonb, 'Позвонить', 'tel:+12155550100', 10, true),
('ru', 'service-detail', 'overview', 'Описание услуги', 'Что включает услуга', 'Используйте этот блок для общего описания. Конкретные title, intro, excerpt и SEO идут из Services admin.', '[]'::jsonb, null, null, 20, true),
('ru', 'service-detail', 'readiness', null, 'Что клиенту подготовить', 'Попросите марку, модель, год, текущую локацию, телефон, срочность и информацию о том, потеряны ли все ключи.', '["Марка, модель и год", "Точная локация", "Ситуация с ключом", "Телефон для подтверждения"]'::jsonb, null, null, 30, true),
('ru', 'service-detail', 'pricing', null, 'Что влияет на цену и сроки', 'Финальная цена и время могут зависеть от системы безопасности авто, типа ключа, наличия деталей, программирования, расстояния, времени и сложности.', '["Система безопасности авто", "Тип ключа или брелка", "Наличие деталей", "Необходимость программирования", "Расстояние и время"]'::jsonb, null, null, 40, true),
('ru', 'service-detail', 'authorization', null, 'Авторизация и безопасность', 'Клиенту может потребоваться подтвердить право доступа или обслуживания автомобиля до начала работы.', '["Может потребоваться подтверждение права", "Детали подтверждаются до начала", "Безопасность и защита от мошенничества важны"]'::jsonb, null, null, 50, true),
('ru', 'service-detail', 'process', 'Как проходит заявка', 'Процесс заявки', 'Объясните путь клиента от заявки до подтверждения.', '["Отправить услугу и данные авто", "Подтвердить локацию, срочность и телефон", "Проверить доступность, детали и программирование", "Подтвердить следующий шаг до начала услуги"]'::jsonb, null, null, 60, true),

-- RU / AREA DETAIL
('ru', 'area-detail', 'hero', 'Локальное покрытие авто-сервиса', '', 'Эта страница объясняет мобильную доступность, частые заявки и подготовку клиента в этом районе.', '[]'::jsonb, 'Позвонить', 'tel:+12155550100', 10, true),
('ru', 'area-detail', 'overview', 'Описание района', 'Информация о мобильном покрытии', 'Используйте этот блок для общего описания. Город, title, intro, услуги и SEO идут из Areas admin.', '[]'::jsonb, null, null, 20, true),
('ru', 'area-detail', 'prep', null, 'Что подготовить перед услугой', 'Клиент должен подготовить данные автомобиля и локацию перед запросом мобильной услуги.', '["Марка, модель и год", "Точный адрес или ориентир", "Потеряны ли все ключи", "Машина закрыта, заведена или в гараже", "Телефон для подтверждения"]'::jsonb, null, null, 30, true),
('ru', 'area-detail', 'supported-services', null, 'Частые услуги здесь', 'Объясните частые услуги на локальных страницах.', '["Открытие авто", "Замена ключей", "Программирование брелков и transponder", "Извлечение сломанного ключа", "Помощь с зажиганием"]'::jsonb, null, null, 40, true),
('ru', 'area-detail', 'local-info', null, 'Локальная информация', 'Объясните, как работает локальная доступность.', '["Мобильный сервис зависит от доступности и локации", "Сроки зависят от трафика, расстояния, погоды и срочности", "Цена зависит от автомобиля, деталей и сложности"]'::jsonb, null, null, 50, true),
('ru', 'area-detail', 'coverage-notes', null, 'Заметки по покрытию', 'Уточните ограничения покрытия и ожидания клиента.', '["Покрытие может меняться по времени и доступности", "Некоторые авто требуют специальные детали или инструменты", "Детали подтверждаются до начала услуги"]'::jsonb, null, null, 60, true)
on conflict do nothing;
