import type { AdminContentBlockPreset } from '@/lib/admin/content-block-types'

export const adminContentBlockPresets: AdminContentBlockPreset[] = [
  { group: 'Services', label: 'Services hero', description: 'Main hero module on the services listing page.', usedOn: '/services', fields: 'eyebrow, title, body, items[0], CTA', pageKey: 'services', slot: 'hero', eyebrow: 'Planetlocksmiths / services', title: 'Automotive Locksmith Services', body: 'Mobile automotive locksmith help for lockouts, replacement keys, key fob programming, transponder keys, ignition issues, and broken key situations.', itemsText: 'Call', ctaLabel: 'Request service', ctaHref: '/en/contact#request-service' },
  { group: 'Services', label: 'Services side card', description: 'Right-side support card beside the services hero.', usedOn: '/services', fields: 'title, body, items[0]', pageKey: 'services', slot: 'side', title: 'Service request ready', body: 'Choose a service page, review what details are needed, then call or submit a request with vehicle make, model, year, location, and urgency.', itemsText: 'Published services' },
  { group: 'Services', label: 'Services card labels', description: 'Small card prefix and open-link label for service cards.', usedOn: '/services', fields: 'eyebrow, CTA label', pageKey: 'services', slot: 'cards', eyebrow: 'Service', ctaLabel: 'Open page' },
  { group: 'Services', label: 'Services trust checklist', description: 'Premium trust checklist rendered below the services hero.', usedOn: '/services', fields: 'eyebrow, title, body, items, CTA', pageKey: 'services', slot: 'trust-section', eyebrow: 'Request confidence', title: 'Clear service flow before work begins', body: 'Each automotive locksmith request is easier to route when the service type, vehicle details, location, and urgency are clear.', itemsText: 'Vehicle-specific request details\nMobile-first contact path\nClear callback information\nService scope confirmed before work begins', ctaLabel: 'Start request', ctaHref: '/en/contact#request-service' },
  { group: 'Services', label: 'Services preparation module', description: 'Extra services page module explaining what customers should prepare.', usedOn: '/services', fields: 'eyebrow, title, body, items', pageKey: 'services', slot: 'prep-section', eyebrow: 'Before you request service', title: 'Information that helps speed up the callback', body: 'Better details help confirm the right next step for lockouts, replacement keys, fobs, transponders, ignition issues, and broken key situations.', itemsText: 'Vehicle make, model, and year\nExact location or ZIP code\nKey situation and urgency\nPhone number for confirmation' },

  { group: 'Service detail', label: 'Service detail process', description: 'Four-step process grid on every service detail page.', usedOn: '/services/[slug]', fields: 'eyebrow, title, body, items', pageKey: 'service-detail', slot: 'process', eyebrow: 'How the request works', title: 'Simple request flow', body: 'The process stays clear before any service is confirmed.', itemsText: 'Submit service and vehicle details\nConfirm location, urgency, and phone number\nReview availability, parts, and programming needs\nConfirm next step before service begins' },
  { group: 'Service detail', label: 'Service readiness card', description: 'Small readiness card on service detail pages.', usedOn: '/services/[slug]', fields: 'title, body, items', pageKey: 'service-detail', slot: 'readiness', title: 'Information customers should prepare', body: 'Vehicle make, model, year, current location, urgency, and whether all keys are lost help make the request actionable.' },
  { group: 'Service detail', label: 'Service pricing card', description: 'Small card explaining what affects price and timing.', usedOn: '/services/[slug]', fields: 'title, body, items', pageKey: 'service-detail', slot: 'pricing', title: 'What affects price and timing', body: 'Final pricing can depend on vehicle security system, key type, programming requirements, parts availability, distance, timing, and job complexity.' },
  { group: 'Service detail', label: 'Service authorization card', description: 'Small card explaining ownership and authorization checks.', usedOn: '/services/[slug]', fields: 'title, body, items', pageKey: 'service-detail', slot: 'authorization', title: 'Authorization and safety', body: 'Customers may be asked to confirm authorization to access or service the vehicle before work begins.' },

  { group: 'Areas', label: 'Areas hero', description: 'Main hero module on the areas listing page.', usedOn: '/areas', fields: 'eyebrow, title, body, items[0], CTA', pageKey: 'areas', slot: 'hero', eyebrow: 'Planetlocksmiths / coverage', title: 'Mobile Locksmith Service Areas', body: 'Explore automotive locksmith coverage areas and request help with vehicle lockouts, keys, fobs, programming, and ignition-related service.', itemsText: 'Call', ctaLabel: 'Request service', ctaHref: '/en/contact#request-service' },
  { group: 'Areas', label: 'Areas side card', description: 'Right-side support card beside the areas hero.', usedOn: '/areas', fields: 'title, body, items[0]', pageKey: 'areas', slot: 'side', title: 'Coverage ready', body: 'Select a service area to review local coverage details, then submit the vehicle, location, and urgency.', itemsText: 'Published areas' },
  { group: 'Areas', label: 'Area card labels', description: 'Small card prefix and open-link label for area cards.', usedOn: '/areas', fields: 'eyebrow, CTA label', pageKey: 'areas', slot: 'cards', eyebrow: 'Area', ctaLabel: 'Open area' },
  { group: 'Areas', label: 'Areas coverage trust', description: 'Premium coverage trust module rendered under the areas hero.', usedOn: '/areas', fields: 'eyebrow, title, body, items', pageKey: 'areas', slot: 'coverage-trust', eyebrow: 'Coverage clarity', title: 'Local pages built around real service details', body: 'Coverage pages help customers understand where service may be available and what details are needed before requesting help.', itemsText: 'Location and ZIP code\nVehicle make, model, and year\nService type and urgency\nPhone number for confirmation' },
  { group: 'Areas', label: 'Areas availability notes', description: 'Extra module explaining coverage variables.', usedOn: '/areas', fields: 'eyebrow, title, body, items', pageKey: 'areas', slot: 'availability-notes', eyebrow: 'Availability', title: 'Coverage depends on job and location factors', body: 'Mobile automotive locksmith availability can change based on distance, technician schedule, parts, weather, traffic, and vehicle requirements.', itemsText: 'Technician availability\nDistance and current traffic\nVehicle security system\nParts and programming requirements' },

  { group: 'Area detail', label: 'Area prep card', description: 'Preparation checklist on every area detail page.', usedOn: '/areas/[slug]', fields: 'title, body, items', pageKey: 'area-detail', slot: 'prep', title: 'What to prepare before service', itemsText: 'Vehicle make, model, and year\nExact address, parking lot, or nearby landmark\nWhether all keys are lost\nWhether the vehicle is locked, running, or in a garage\nPhone number for fast confirmation' },
  { group: 'Area detail', label: 'Area supported services', description: 'Supported service list on area detail pages.', usedOn: '/areas/[slug]', fields: 'title, body, items', pageKey: 'area-detail', slot: 'supported-services', title: 'Services commonly requested here', itemsText: 'Car lockout help\nReplacement car keys\nKey fob and transponder programming\nBroken key extraction\nIgnition-related support' },
  { group: 'Area detail', label: 'Area local info', description: 'Local service notes on area detail pages.', usedOn: '/areas/[slug]', fields: 'title, body, items', pageKey: 'area-detail', slot: 'local-info', title: 'Local service information', itemsText: 'Mobile service depends on technician availability and location\nResponse times may vary by traffic, distance, weather, and urgency\nFinal price depends on vehicle details, parts, and job complexity' },
  { group: 'Area detail', label: 'Area coverage notes', description: 'Coverage limitations and confirmation notes.', usedOn: '/areas/[slug]', fields: 'title, body, items', pageKey: 'area-detail', slot: 'coverage-notes', title: 'Coverage notes', itemsText: 'Mobile service availability is not guaranteed until confirmed\nParts and programming support depend on vehicle details\nFinal service scope should be confirmed before work begins' },

  { group: 'Contact', label: 'Contact hero', description: 'Main contact page hero module.', usedOn: '/contact', fields: 'eyebrow, title, body, items[0], CTA', pageKey: 'contact', slot: 'hero', eyebrow: 'Contact Planetlocksmiths', title: 'Request mobile automotive locksmith service', body: 'Use the form below to send vehicle details, location, urgency, and the service needed. For urgent lockouts or active roadside situations, calling may be faster.', itemsText: 'Call', ctaLabel: 'Request service', ctaHref: '#request-service' },
  { group: 'Contact', label: 'Contact side card', description: 'Right-side helper card on contact page.', usedOn: '/contact', fields: 'title, body', pageKey: 'contact', slot: 'side', title: 'What makes the request faster', body: 'Vehicle make, model, year, exact location, phone number, and key situation help create a cleaner callback and service path.' },
  { group: 'Contact', label: 'Contact service tile', description: 'Small info tile describing service type.', usedOn: '/contact', fields: 'title, body', pageKey: 'contact', slot: 'info-service', title: 'Service type', body: 'Mobile automotive locksmith' },
  { group: 'Contact', label: 'Contact area tile', description: 'Small info tile describing coverage area.', usedOn: '/contact', fields: 'title, body', pageKey: 'contact', slot: 'info-area', title: 'Common area', body: 'Philadelphia, Pennsylvania and nearby coverage areas' },
  { group: 'Contact', label: 'Contact helper', description: 'Fallback helper copy used by the contact page.', usedOn: '/contact', fields: 'eyebrow, title, body', pageKey: 'contact', slot: 'helper', eyebrow: 'Request details', title: 'Fast service needs clear vehicle information', body: 'Phone, service, vehicle make, model, year, current location, and urgency help route the request correctly.' },
  { group: 'Contact', label: 'Contact request checklist', description: 'Premium checklist module above the contact form.', usedOn: '/contact', fields: 'eyebrow, title, body, items', pageKey: 'contact', slot: 'request-checklist', eyebrow: 'Before submitting', title: 'What to include in your request', body: 'Complete request details make the callback cleaner and reduce back-and-forth.', itemsText: 'Vehicle make, model, and year\nExact location\nService type\nUrgency\nWorking phone number' },

  { group: 'About', label: 'About hero', description: 'Main about page hero module.', usedOn: '/about', fields: 'eyebrow, title, body', pageKey: 'about', slot: 'hero', eyebrow: 'About Planetlocksmiths', title: 'Mobile automotive locksmith support built for clear, fast service requests.', body: 'Planetlocksmiths is structured around mobile automotive locksmith requests for car lockouts, replacement keys, key fob programming, transponder support, ignition-related help, and broken key situations.' },
  { group: 'About', label: 'About automotive focus', description: 'About page premium content card.', usedOn: '/about', fields: 'eyebrow, title, body', pageKey: 'about', slot: 'section-1', eyebrow: 'About 01', title: 'Automotive focus', body: 'The site is designed around vehicle-specific requests so customers can provide service type, vehicle details, location, urgency, and contact information clearly.' },
  { group: 'About', label: 'About mobile service path', description: 'About page service path card.', usedOn: '/about', fields: 'eyebrow, title, body', pageKey: 'about', slot: 'section-2', eyebrow: 'About 02', title: 'Mobile-first service path', body: 'Customers can call or submit a request from any page. Service availability depends on location, vehicle details, parts, timing, and job complexity.' },
  { group: 'About', label: 'About info checklist', description: 'About page checklist card.', usedOn: '/about', fields: 'eyebrow, title, body, items', pageKey: 'about', slot: 'section-3', eyebrow: 'About 03', title: 'Information that matters', body: 'Cleaner request details help confirm the right next step before service begins.', itemsText: 'Vehicle make, model, and year\nCurrent location or ZIP code\nLockout, lost key, fob, transponder, ignition, or broken key situation\nPhone number and urgency' },

  { group: 'FAQ', label: 'FAQ hero', description: 'Main FAQ page hero module.', usedOn: '/faq', fields: 'eyebrow, title, body', pageKey: 'faq', slot: 'hero', eyebrow: 'Customer questions', title: 'Frequently Asked Questions', body: 'Answers to common questions about mobile automotive locksmith requests, service timing, vehicle information, key programming, and availability.' },
  { group: 'FAQ', label: 'FAQ empty state', description: 'Text shown only when no FAQ items are published.', usedOn: '/faq', fields: 'body', pageKey: 'faq', slot: 'empty', body: 'No published FAQ items yet.' },
  { group: 'FAQ', label: 'FAQ service expectations', description: 'Premium FAQ intro module above FAQ list.', usedOn: '/faq', fields: 'eyebrow, title, body, items', pageKey: 'faq', slot: 'service-expectations', eyebrow: 'Before you call', title: 'What customers should know before requesting help', body: 'Automotive locksmith requests are easier to confirm when the vehicle, location, and key situation are clear.', itemsText: 'Pricing depends on vehicle details\nAvailability depends on location and timing\nAuthorization may be required\nParts and programming needs can affect service scope' },
  { group: 'FAQ', label: 'FAQ request clarity', description: 'Extra FAQ support module.', usedOn: '/faq', fields: 'eyebrow, title, body, items', pageKey: 'faq', slot: 'request-clarity', eyebrow: 'Request clarity', title: 'Clear details reduce delays', body: 'The fastest requests usually include exact vehicle and location information.', itemsText: 'Make, model, and year\nExact location\nCurrent key status\nPhone number and urgency' },

  { group: 'Reviews', label: 'Reviews hero', description: 'Main reviews page hero module.', usedOn: '/reviews', fields: 'eyebrow, title, body', pageKey: 'reviews', slot: 'hero', eyebrow: 'Customer feedback', title: 'Customer Reviews', body: 'Read customer feedback for mobile automotive locksmith requests including lockouts, replacement keys, fobs, transponder support, and related vehicle key situations.' },
  { group: 'Reviews', label: 'Reviews empty state', description: 'Text shown only when no reviews are published.', usedOn: '/reviews', fields: 'body', pageKey: 'reviews', slot: 'empty', body: 'No published reviews yet.' },
  { group: 'Reviews', label: 'Reviews trust notes', description: 'Premium reviews support module.', usedOn: '/reviews', fields: 'eyebrow, title, body, items', pageKey: 'reviews', slot: 'trust-notes', eyebrow: 'Trust signals', title: 'Reviews help customers understand the service path', body: 'Published reviews can show how customers describe response quality, communication, and automotive key situations.', itemsText: 'Clear customer feedback\nMobile service context\nAutomotive locksmith use cases\nLocal request confidence' },
  { group: 'Reviews', label: 'Reviews guidance', description: 'Extra reviews guidance module.', usedOn: '/reviews', fields: 'eyebrow, title, body, items', pageKey: 'reviews', slot: 'review-guidance', eyebrow: 'Customer proof', title: 'What good reviews should communicate', body: 'Strong reviews are specific, vehicle-related, and clear about the customer experience.', itemsText: 'Service type\nVehicle situation\nCommunication quality\nLocation context' },

  { group: 'Legal', label: 'Legal privacy hero', description: 'Main privacy policy hero module.', usedOn: '/privacy', fields: 'eyebrow, title, body', pageKey: 'legal-privacy', slot: 'hero', eyebrow: 'Customer information', title: 'Privacy Policy', body: 'This page explains how Planetlocksmiths handles information submitted through this website for mobile automotive locksmith service requests.' },
  { group: 'Legal', label: 'Legal privacy section', description: 'Reusable privacy policy section. Duplicate and change slot to section-2, section-3, etc.', usedOn: '/privacy', fields: 'title, body, items', pageKey: 'legal-privacy', slot: 'section-1', title: 'Information we collect', body: 'When you submit a service request, we may collect your name, phone number, email address, requested service, vehicle make/model/year, service location, urgency, preferred time, and message details.' },
  { group: 'Legal', label: 'Legal terms hero', description: 'Main terms page hero module.', usedOn: '/terms', fields: 'eyebrow, title, body', pageKey: 'legal-terms', slot: 'hero', eyebrow: 'Customer information', title: 'Terms of Service', body: 'These terms explain the basic conditions for using this website and submitting a mobile automotive locksmith service request to Planetlocksmiths.' },
  { group: 'Legal', label: 'Legal terms section', description: 'Reusable terms section. Duplicate and change slot to section-2, section-3, etc.', usedOn: '/terms', fields: 'title, body, items', pageKey: 'legal-terms', slot: 'section-1', title: 'Website use', body: 'This website provides information about automotive locksmith services and allows customers to submit service requests. You agree to provide accurate contact, vehicle, and location details when requesting service.' },
]

export const adminContentBlockPresetGroups = Array.from(new Set(adminContentBlockPresets.map((preset) => preset.group)))
export const adminContentBlockKnownPageKeys = Array.from(new Set(adminContentBlockPresets.map((preset) => preset.pageKey))).sort()
