import type { AdminContentBlockPreset } from '@/lib/admin/content-block-types'

export const adminContentBlockPresets: AdminContentBlockPreset[] = [
  { group: 'Services', label: 'Services hero', description: 'Main hero module on the services listing page.', usedOn: '/services', fields: 'eyebrow, title, body, items[0], CTA', pageKey: 'services', slot: 'hero', eyebrow: 'Planet Locksmiths / services', title: 'Locksmith Services', body: 'Mobile locksmith help for car lockouts, all keys lost, key programming, rekeys, lock repair, lock replacement, residential, commercial, access control, safe opening, and emergency service requests.', itemsText: 'Call', ctaLabel: 'Request service', ctaHref: '/en/contact#request-service' },
  { group: 'Services', label: 'Services side card', description: 'Right-side support card beside the services hero.', usedOn: '/services', fields: 'title, body, items[0]', pageKey: 'services', slot: 'side', title: 'Service request ready', body: 'Choose a service page, review what details are needed, then call or submit a request with service type, location, phone number, urgency, and vehicle details when relevant.', itemsText: 'Published services' },
  { group: 'Services', label: 'Services card labels', description: 'Small card prefix and open-link label for service cards.', usedOn: '/services', fields: 'eyebrow, CTA label', pageKey: 'services', slot: 'cards', eyebrow: 'Service', ctaLabel: 'Open page' },
  { group: 'Services', label: 'Services trust checklist', description: 'Premium trust checklist rendered below the services hero.', usedOn: '/services', fields: 'eyebrow, title, body, items, CTA', pageKey: 'services', slot: 'trust-section', eyebrow: 'Request confidence', title: 'Clear service flow before work begins', body: 'Each locksmith request is easier to route when the service type, location, authorization, and urgency are clear.', itemsText: 'Service-specific request details\nMobile-first contact path\nClear callback information\nService scope confirmed before work begins', ctaLabel: 'Start request', ctaHref: '/en/contact#request-service' },
  { group: 'Services', label: 'Services preparation module', description: 'Extra services page module explaining what customers should prepare.', usedOn: '/services', fields: 'eyebrow, title, body, items', pageKey: 'services', slot: 'prep-section', eyebrow: 'Before you request service', title: 'Information that helps speed up the callback', body: 'Better details help confirm the right next step for lockouts, lost keys, rekeys, fobs, access control, safe opening, lock repair, lock replacement, and broken key situations.', itemsText: 'Service type and access details\nExact location or ZIP code\nKey, lock, door, safe, mailbox, or vehicle situation\nPhone number for confirmation' },

  { group: 'Service detail', label: 'Service detail process', description: 'Four-step process grid on every service detail page.', usedOn: '/services/[slug]', fields: 'eyebrow, title, body, items', pageKey: 'service-detail', slot: 'process', eyebrow: 'How the request works', title: 'Simple request flow', body: 'The process stays clear before any service is confirmed.', itemsText: 'Submit service details and location\nConfirm urgency, authorization, and phone number\nReview availability, tools, parts, and compatibility\nConfirm next step before service begins' },
  { group: 'Service detail', label: 'Service readiness card', description: 'Small readiness card on service detail pages.', usedOn: '/services/[slug]', fields: 'title, body, items', pageKey: 'service-detail', slot: 'readiness', title: 'Information customers should prepare', body: 'Service type, exact location, urgency, phone number, authorization details, and vehicle information when relevant help make the request actionable.' },
  { group: 'Service detail', label: 'Service pricing card', description: 'Small card explaining what affects price and timing.', usedOn: '/services/[slug]', fields: 'title, body, items', pageKey: 'service-detail', slot: 'pricing', title: 'What affects price and timing', body: 'Final pricing can depend on service type, lock or key system, programming requirements, parts availability, distance, timing, authorization, and job complexity.' },
  { group: 'Service detail', label: 'Service authorization card', description: 'Small card explaining ownership and authorization checks.', usedOn: '/services/[slug]', fields: 'title, body, items', pageKey: 'service-detail', slot: 'authorization', title: 'Authorization and safety', body: 'Customers may be asked to confirm authorization to access or service the vehicle, property, door, lock, safe, mailbox, or access-control system before work begins.' },

  { group: 'Areas', label: 'Areas hero', description: 'Main hero module on the areas listing page.', usedOn: '/areas', fields: 'eyebrow, title, body, items[0], CTA', pageKey: 'areas', slot: 'hero', eyebrow: 'Planet Locksmiths / coverage', title: 'Mobile Locksmith Service Areas', body: 'Explore locksmith coverage areas and request help with lockouts, car keys, rekeys, commercial locks, residential locks, safe opening, and emergency service.', itemsText: 'Call', ctaLabel: 'Request service', ctaHref: '/en/contact#request-service' },
  { group: 'Areas', label: 'Areas side card', description: 'Right-side support card beside the areas hero.', usedOn: '/areas', fields: 'title, body, items[0]', pageKey: 'areas', slot: 'side', title: 'Coverage ready', body: 'Select a service area to review local coverage details, then submit the service type, location, phone number, and urgency.', itemsText: 'Published areas' },
  { group: 'Areas', label: 'Area card labels', description: 'Small card prefix and open-link label for area cards.', usedOn: '/areas', fields: 'eyebrow, CTA label', pageKey: 'areas', slot: 'cards', eyebrow: 'Area', ctaLabel: 'Open area' },
  { group: 'Areas', label: 'Areas coverage trust', description: 'Premium coverage trust module rendered under the areas hero.', usedOn: '/areas', fields: 'eyebrow, title, body, items', pageKey: 'areas', slot: 'coverage-trust', eyebrow: 'Coverage clarity', title: 'Local pages built around real service details', body: 'Coverage pages help customers understand where service may be available and what details are needed before requesting help.', itemsText: 'Location and ZIP code\nService type and urgency\nAccess or authorization details\nPhone number for confirmation' },
  { group: 'Areas', label: 'Areas availability notes', description: 'Extra module explaining coverage variables.', usedOn: '/areas', fields: 'eyebrow, title, body, items', pageKey: 'areas', slot: 'availability-notes', eyebrow: 'Availability', title: 'Coverage depends on job and location factors', body: 'Mobile locksmith availability can change based on distance, technician schedule, parts, weather, traffic, service type, and access requirements.', itemsText: 'Technician availability\nDistance and current traffic\nLock, key, safe, door, or access system\nParts and programming requirements' },

  { group: 'Area detail', label: 'Area prep card', description: 'Preparation checklist on every area detail page.', usedOn: '/areas/[slug]', fields: 'title, body, items', pageKey: 'area-detail', slot: 'prep', title: 'What to prepare before service', itemsText: 'Service needed and exact location\nLock, door, safe, mailbox, or access-control details\nVehicle make, model, and year when relevant\nWhether keys are lost, broken, locked in, or not programming\nPhone number for fast confirmation' },
  { group: 'Area detail', label: 'Area supported services', description: 'Supported service list on area detail pages.', usedOn: '/areas/[slug]', fields: 'title, body, items', pageKey: 'area-detail', slot: 'supported-services', title: 'Services commonly requested here', itemsText: 'Emergency locksmith 24/7\nCar lockout help\nRekey service\nCommercial locksmith\nResidential locksmith' },
  { group: 'Area detail', label: 'Area local info', description: 'Local service notes on area detail pages.', usedOn: '/areas/[slug]', fields: 'title, body, items', pageKey: 'area-detail', slot: 'local-info', title: 'Local service information', itemsText: 'Mobile service depends on technician availability and location\nResponse times may vary by traffic, distance, weather, and urgency\nFinal price depends on service details, parts, authorization, and job complexity' },
  { group: 'Area detail', label: 'Area coverage notes', description: 'Coverage limitations and confirmation notes.', usedOn: '/areas/[slug]', fields: 'title, body, items', pageKey: 'area-detail', slot: 'coverage-notes', title: 'Coverage notes', itemsText: 'Mobile service availability is not guaranteed until confirmed\nParts and programming support depend on service details\nFinal service scope should be confirmed before work begins' },

  { group: 'Contact', label: 'Contact hero', description: 'Main contact page hero module.', usedOn: '/contact', fields: 'eyebrow, title, body, items[0], CTA', pageKey: 'contact', slot: 'hero', eyebrow: 'Contact Planet Locksmiths', title: 'Request mobile locksmith service', body: 'Use the form below to send service details, location, urgency, and contact information. For urgent lockouts, lost keys, business access problems, or safe issues, calling may be faster.', itemsText: 'Call', ctaLabel: 'Request service', ctaHref: '#request-service' },
  { group: 'Contact', label: 'Contact side card', description: 'Right-side helper card on contact page.', usedOn: '/contact', fields: 'title, body', pageKey: 'contact', slot: 'side', title: 'What makes the request faster', body: 'Service type, exact location, phone number, urgency, access authorization, and vehicle details when relevant help create a cleaner callback path.' },
  { group: 'Contact', label: 'Contact service tile', description: 'Small info tile describing service type.', usedOn: '/contact', fields: 'title, body', pageKey: 'contact', slot: 'info-service', title: 'Service type', body: 'Mobile locksmith service' },
  { group: 'Contact', label: 'Contact area tile', description: 'Small info tile describing coverage area.', usedOn: '/contact', fields: 'title, body', pageKey: 'contact', slot: 'info-area', title: 'Common area', body: 'Philadelphia, Pennsylvania and nearby coverage areas' },
  { group: 'Contact', label: 'Contact helper', description: 'Fallback helper copy used by the contact page.', usedOn: '/contact', fields: 'eyebrow, title, body', pageKey: 'contact', slot: 'helper', eyebrow: 'Request details', title: 'Fast service needs clear request information', body: 'Phone, service type, exact location, urgency, authorization, and optional vehicle or property details help route the request correctly.' },
  { group: 'Contact', label: 'Contact request checklist', description: 'Premium checklist module above the contact form.', usedOn: '/contact', fields: 'eyebrow, title, body, items', pageKey: 'contact', slot: 'request-checklist', eyebrow: 'Before submitting', title: 'What to include in your request', body: 'Complete request details make the callback cleaner and reduce back-and-forth.', itemsText: 'Service type\nExact location\nAuthorization or access details\nUrgency\nWorking phone number' },

  { group: 'About', label: 'About hero', description: 'Main about page hero module.', usedOn: '/about', fields: 'eyebrow, title, body', pageKey: 'about', slot: 'hero', eyebrow: 'About Planet Locksmiths', title: 'Mobile locksmith support built for clear, fast service requests.', body: 'Planet Locksmiths is structured around mobile locksmith requests for lockouts, car keys, programming, rekeys, lock repair, lock replacement, residential, commercial, access control, safe opening, and urgent key situations.' },
  { group: 'About', label: 'About service focus', description: 'About page premium content card.', usedOn: '/about', fields: 'eyebrow, title, body', pageKey: 'about', slot: 'section-1', eyebrow: 'About 01', title: 'Full locksmith scope', body: 'The site is designed around auto, residential, commercial, rekey, installation, safe opening, access control, and emergency service requests.' },
  { group: 'About', label: 'About mobile service path', description: 'About page service path card.', usedOn: '/about', fields: 'eyebrow, title, body', pageKey: 'about', slot: 'section-2', eyebrow: 'About 02', title: 'Mobile-first service path', body: 'Customers can call or submit a request from any page. Service availability depends on location, service type, parts, timing, authorization, and job complexity.' },
  { group: 'About', label: 'About info checklist', description: 'About page checklist card.', usedOn: '/about', fields: 'eyebrow, title, body, items', pageKey: 'about', slot: 'section-3', eyebrow: 'About 03', title: 'Information that matters', body: 'Cleaner request details help confirm the right next step before service begins.', itemsText: 'Service needed and current location\nVehicle details when relevant\nLock, door, safe, mailbox, or access-control details\nPhone number and urgency' },

  { group: 'FAQ', label: 'FAQ hero', description: 'Main FAQ page hero module.', usedOn: '/faq', fields: 'eyebrow, title, body', pageKey: 'faq', slot: 'hero', eyebrow: 'Customer questions', title: 'Frequently Asked Questions', body: 'Answers to common questions about mobile locksmith requests, service timing, car keys, rekeys, commercial locks, residential locks, access control, safe opening, and availability.' },
  { group: 'FAQ', label: 'FAQ empty state', description: 'Text shown only when no FAQ items are published.', usedOn: '/faq', fields: 'body', pageKey: 'faq', slot: 'empty', body: 'No published FAQ items yet.' },
  { group: 'FAQ', label: 'FAQ service expectations', description: 'Premium FAQ intro module above FAQ list.', usedOn: '/faq', fields: 'eyebrow, title, body, items', pageKey: 'faq', slot: 'service-expectations', eyebrow: 'Before you call', title: 'What customers should know before requesting help', body: 'Locksmith requests are easier to confirm when the service type, location, authorization, and issue are clear.', itemsText: 'Pricing depends on service details\nAvailability depends on location and timing\nAuthorization may be required\nParts and programming needs can affect service scope' },
  { group: 'FAQ', label: 'FAQ request clarity', description: 'Extra FAQ support module.', usedOn: '/faq', fields: 'eyebrow, title, body, items', pageKey: 'faq', slot: 'request-clarity', eyebrow: 'Request clarity', title: 'Clear details reduce delays', body: 'The fastest requests usually include exact service and location information.', itemsText: 'Service type\nExact location\nCurrent key, lock, door, safe, or access status\nPhone number and urgency' },

  { group: 'Reviews', label: 'Reviews hero', description: 'Main reviews page hero module.', usedOn: '/reviews', fields: 'eyebrow, title, body', pageKey: 'reviews', slot: 'hero', eyebrow: 'Customer feedback', title: 'Customer Reviews', body: 'Read customer feedback for mobile locksmith requests including lockouts, replacement keys, fobs, rekeys, lock repair, commercial access, and residential service situations.' },
  { group: 'Reviews', label: 'Reviews empty state', description: 'Text shown only when no reviews are published.', usedOn: '/reviews', fields: 'body', pageKey: 'reviews', slot: 'empty', body: 'No published reviews yet.' },
  { group: 'Reviews', label: 'Reviews trust notes', description: 'Premium reviews support module.', usedOn: '/reviews', fields: 'eyebrow, title, body, items', pageKey: 'reviews', slot: 'trust-notes', eyebrow: 'Trust signals', title: 'Reviews help customers understand the service path', body: 'Published reviews can show how customers describe response quality, communication, and locksmith service situations.', itemsText: 'Clear customer feedback\nMobile service context\nLocksmith use cases\nLocal request confidence' },
  { group: 'Reviews', label: 'Reviews guidance', description: 'Extra reviews guidance module.', usedOn: '/reviews', fields: 'eyebrow, title, body, items', pageKey: 'reviews', slot: 'review-guidance', eyebrow: 'Customer proof', title: 'What good reviews should communicate', body: 'Strong reviews are specific, service-related, and clear about the customer experience.', itemsText: 'Service type\nLock, key, door, safe, or vehicle situation\nCommunication quality\nLocation context' },

  { group: 'Legal', label: 'Legal privacy hero', description: 'Main privacy policy hero module.', usedOn: '/privacy', fields: 'eyebrow, title, body', pageKey: 'legal-privacy', slot: 'hero', eyebrow: 'Customer information', title: 'Privacy Policy', body: 'This page explains how Planet Locksmiths handles information submitted through this website for mobile locksmith service requests.' },
  { group: 'Legal', label: 'Legal privacy section', description: 'Reusable privacy policy section. Duplicate and change slot to section-2, section-3, etc.', usedOn: '/privacy', fields: 'title, body, items', pageKey: 'legal-privacy', slot: 'section-1', title: 'Information we collect', body: 'When you submit a service request, we may collect your name, phone number, email address, requested service, authorization details, vehicle details when relevant, service location, urgency, preferred time, and message details.' },
  { group: 'Legal', label: 'Legal terms hero', description: 'Main terms page hero module.', usedOn: '/terms', fields: 'eyebrow, title, body', pageKey: 'legal-terms', slot: 'hero', eyebrow: 'Customer information', title: 'Terms of Service', body: 'These terms explain the basic conditions for using this website and submitting a mobile locksmith service request to Planet Locksmiths.' },
  { group: 'Legal', label: 'Legal terms section', description: 'Reusable terms section. Duplicate and change slot to section-2, section-3, etc.', usedOn: '/terms', fields: 'title, body, items', pageKey: 'legal-terms', slot: 'section-1', title: 'Website use', body: 'This website provides information about locksmith services and allows customers to submit service requests. You agree to provide accurate contact, service, authorization, location, and vehicle details when relevant.' },
]

export const adminContentBlockPresetGroups = Array.from(new Set(adminContentBlockPresets.map((preset) => preset.group)))
export const adminContentBlockKnownPageKeys = Array.from(new Set(adminContentBlockPresets.map((preset) => preset.pageKey))).sort()
